### ISSUE TITLE
[web] Initial scroll index example is blank until first scroll

### ISSUE THREAD

**Issue by robingullo** [LegendApp/legend-list#135]
https://github.com/user-attachments/assets/50dc6d0e-c1ad-4133-81fc-629a9f4e1fc9

Version : 1.0.0-beta.15
Reproducing steps :
- run the example app on web
- click "Initial scroll index precise navigation" => the page is blank
- scroll => see first element (instead of 50th)

The issue comes from `contentOffset` not being supported in react-native-web : https://github.com/necolas/react-native-web/issues/1273
A workaround would be to trigger the initial scroll in a ref callback / useLayoutEffect with `behavior: 'instant'`

**Comment by robingullo** [comment]
I have tested the proposed workaround for contentOffset, it works fine in the first example. But in the free height example, initial offset calculation is off, it's only the approximate offset depending on estimatedHeight. So it's likely more complicated.

Example (initialScrollIndex = 10) : it should start at 10 (here it's a bit below) and when scrolling up there is a gap between 1 and 2

https://github.com/user-attachments/assets/e354e283-a423-432e-a605-b72ba21c31bc

**Comment by jmeistrich** [comment]
This should be fixed in beta.25. Is it looking better for you now?

**Comment by robingullo** [comment]
Works fine! Initial scroll offset error is still there for initial-scroll-index-free-height example but it's another issue I think?

**Comment by jmeistrich** [comment]
Ah good catch, thanks! I fixed that one as well. So I believe this is complete and I'll close it. But please let me know if you still see any issues!
