### ISSUE TITLE
regression: paddingTop not being applied

### ISSUE THREAD

**Issue by henninghall** [LegendApp/legend-list#188]
After [this commit ](https://github.com/LegendApp/legend-list/commit/10fa763fe1ec21ffc2102abbf74aec72ce285655) the padding top we are adding in `contentContainerStyle` is not being applied.

No matter what value we add, there will be no visible padding.

Using expo router nested tab and stack navigation.

**Comment by ChronoByteCosmonaut** [comment]
I have the exact same problem 👍

**Comment by jmeistrich** [comment]
Thanks for catching that! I just released beta.43 which should fix it.

**Comment by ChronoByteCosmonaut** [comment]
Hey @jmeistrich seems like the issue is back but only on iOS. Android seems to work. I have a screen where I calculate the height of a component above the list and set the calculated height  as paddingTop of the list because it's absolutely positioned.

**Comment by jmeistrich** [comment]
Did the issue come back in a specific version?

**Comment by ChronoByteCosmonaut** [comment]
I believe it’s been that way since beta 47, if I’m not mistaken! I’ll check it out tonight and let you know.

**Comment by jmeistrich** [comment]
@ChronoByteCosmonaut Were you able to find which version brought the issue back? Maybe it's fixed in the latest 1.0.5?

**Comment by ChronoByteCosmonaut** [comment]
> @ChronoByteCosmonaut Were you able to find which version brought the issue back? Maybe it's fixed in the latest 1.0.5?

Hey @jmeistrich sorry for the late response. I completely forgot about this one 😅. As soon as I get home I'll check it again and also test with the latest version.

**Comment by ChronoByteCosmonaut** [comment]
> @ChronoByteCosmonaut Were you able to find which version brought the issue back? Maybe it's fixed in the latest 1.0.5?

Hey @jmeistrich for me it's fixed in the latest version! Thanks a lot! 🎉

**Comment by jmeistrich** [comment]
Oh that's great! Thanks for checking again :)
