### ISSUE TITLE
Scroll returning to previous position after selecting list item and scrolling again

### ISSUE THREAD

**Issue by matt-unosquare** [LegendApp/legend-list#202]
I am attempting to switch over to LegendList from FlashList and at first everything looked beautiful. The List appears to generate faster, scrolling seems more fluid, but then after testing, when I select an item in the list, it scrolls to said item, but then the next time i try to scroll, after it stops, it reverts back to the scroll position.

I have logged out all of the places where my code tells the item to scroll, and its not being fired, and i logged out where i set the data array and thats also not firing again, so I believe this to be an issue in the LegendList component itself.

Here is a video of this in action. You will see I click an item, it scrolls to that item, then i scroll again and after it finishes it reverts to its previous position. I do that twice in this video

https://github.com/user-attachments/assets/3049214a-5d94-4464-9a74-5a623b668173

Pretty basic JSX
```tsx
<LegendList
  ref={listRef}
  data={filteredVanInventory}
  renderItem={renderItem}
  showsVerticalScrollIndicator={false}
  keyExtractor={item => item.id}
  style={styles.list}
  ListEmptyComponent={EmptyList(locale)}
  ItemSeparatorComponent={Separator}
  maintainScrollAtEnd={true}
/>
```

**Comment by jmeistrich** [comment]
Can you share what your scrolling code looks like? Are you using scrollToIndex? I'm working on another scroll related thing right now, could be related. I'll try to get a fix out tomorrow if I can reproduce it.

**Comment by jmeistrich** [comment]
I just released 1.0.2 which I think should fix it. How's it looking now?

**Comment by matt-unosquare** [comment]
I just downloaded and tried 1.0.3, and the issue still remains for me unfortunately

**Comment by matt-unosquare** [comment]
Looking at 1.0.5 right now... this might be resolved. I am not seeing it on my initial tests

**Comment by jmeistrich** [comment]
Excellent!
