### ISSUE TITLE
Support for RTL in horizontal list

### ISSUE THREAD

**Issue by OmarNashat01** [LegendApp/legend-list#333]
## Current behaviour

When using LegendList in RTL with horizontal scrolling, the list does not render correctly.
Only the first item appears, and the rest of the space is blank. When scrolling, all items disappear completely.

## Example code
```tsx
import { Text, View } from "react-native";
import { LegendList } from "@legendapp/list";

export default function Index() {

  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        gap: 20,
      }}
    >
      <View style={{ height: 320, width: '100%', backgroundColor: 'red', padding: 10 }}>
        <LegendList
          data={Array.from({ length: 100 }, (_, i) => `Item ${i + 1}`)}
          keyExtractor={(item) => item}
          renderItem={({ item }) => (
            <View style={{ padding: 10, borderWidth: 1, borderColor: '#ccc', width: 200, height: 300, justifyContent: 'center', alignItems: 'center', backgroundColor: 'white' }}>
              <Text>
                {item}
              </Text>
            </View>
          )}
          horizontal
          ItemSeparatorComponent={() => <View style={{ width: 10 }} />}
        />
      </View>

      <View style={{ height: 320, width: '100%', direction: 'ltr', backgroundColor: 'blue', padding: 10 }}>
        <LegendList
          data={Array.from({ length: 100 }, (_, i) => `Item ${i + 1}`)}
          keyExtractor={(item) => item}
          renderItem={({ item }) => (
            <View style={{ padding: 10, borderWidth: 1, borderColor: '#ccc', width: 200, height: 300, justifyContent: 'center', alignItems: 'center', backgroundColor: 'white' }}>
              <Text>
                {item}
              </Text>
            </View>
          )}
          horizontal
          ItemSeparatorComponent={() => <View style={{ width: 10 }} />}
        />
      </View>
    </View>
  );
}

```

https://github.com/user-attachments/assets/8096fcac-d2f0-4e07-9f60-8e9b9640e678

## Environment

LegendList version: 2.0.13
React Native version: 0.81.4
Expo SDK version: 54.0.13

**Comment by OmarNashat01** [comment]
Hey [@Im2rnado](https://github.com/Im2rnado),

Initially I had used flashlist v2 with a very large draw distance (bad for performance).
Then I upgraded the project a couple of times and prebuilt everything again and it got flashlist v2 to work correctly.

If you need any help reach out via email (omarnashat01@gmail.com), I can help you debug the issue.

**Comment by Im2rnado** [comment]
Thanks Omar. I will try to check again if I could do it with Flashlist v2. If it doesn’t work out, I’ll see if normal FlatList works well… if not, I will reach out to you and see if you can help. Thanks in advance!

**Comment by liixing** [comment]
@jmeistrich  can we Support RTL in horizontal list ?

**Comment by 2Senn** [comment]
+1

**Comment by jmeistrich** [comment]
I just released 3.0.0-beta.55 to add RTL support. But I am not an expert in RTL so I'd really appreciate it if you could give it a test and let me know if it's working correctly 🙏

**Comment by OmarNashat01** [comment]
Thank you for taking the time to look into this 🙏

I tested `3.0.0-beta.55`, but unfortunately it still doesn’t seem to be working correctly on my side.

I’ll try to take a crack at it over the weekend and share anything useful I find.

**Comment by jmeistrich** [comment]
Thanks @OmarNashat01! I have not used RTL myself so I'm not totally sure how to test it. So if you can give me a repro or steps to reproduce any problems that would be very helpful.

**Comment by OmarNashat01** [comment]
Sorry for the confusion, and thank you again for taking the time to look into this 🙏

I tried creating the reproducer in a fresh environment, and after doing a clean install in the new directory, the issue seems to be resolved there.

So it looks like the problem might be related to something in my original setup rather than LegendList itself.
